#!/bin/bash
CER='.cer'
CRT='.crt'
KEY='.key'
VPNNAME=$(echo $1 | sed -e 's/.ovpn$//g')
mkdir $VPNNAME
sed -n '/<ca>/,/<\/ca>/p' $1 | tail -n +2 > $VPNNAME/$VPNNAME$(echo .cer)
sed -n '/<cert>/,/<\/cert>/p' $1 | tail -n +2 > $VPNNAME/$VPNNAME$(echo .crt)
sed -n '/<key>/,/<\/key>/p' $1 | tail -n +2 > $VPNNAME/$VPNNAME$(echo .key)
mv $1 $VPNNAME


